import Head from "next/head";

import { DynamicQuestionList } from "@/components/questions/QuestionList";
import { cssQuestionsData } from "@/questionsData/cssQuestions";

export default function Home() {
  return (
    <>
      <Head>
        <title>CSS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DynamicQuestionList questions={cssQuestionsData} tech="CSS" />
    </>
  );
}
