import Head from "next/head";
import { Inter } from "next/font/google";

import { DynamicQuestionList } from "@/components/questions/QuestionList";
import { generalQuestionsData } from "@/questionsData/generalQuestions";

export default function Home() {
  return (
    <>
      <Head>
        <title>General</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DynamicQuestionList questions={generalQuestionsData} tech="General" />
    </>
  );
}
