import Head from "next/head";

import QuestionList from "@/components/questions/QuestionList";
import { htmlQuestionsData } from "@/questionsData/htmlQuestions";
import { Flex, Text } from "@mantine/core";

export default function Home() {
  return (
    <>
      <Head>
        <title>HTML</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Text>Welcome to</Text>
      <Text>Front-End questions library</Text>
      <Flex mt="2rem" align="center">
        <Text size="1.3rem">In our base we have </Text>
        <Text mx="0.5rem" size="2rem" pb="0.6rem">
          280
        </Text>
        <Text>questions</Text>
      </Flex> */}
      <QuestionList questions={htmlQuestionsData} tech="HTML" />
    </>
  );
}
