import Head from "next/head";

import { htmlQuestionsData } from "@/questionsData/htmlQuestions";
import { DynamicQuestionList } from "@/components/questions/QuestionList";

export default function Home() {
  return (
    <>
      <Head>
        <title>HTML</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DynamicQuestionList questions={htmlQuestionsData} tech="HTML" />
    </>
  );
}
