import Head from "next/head";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";

import { javascriptQuestionsData } from "@/questionsData/javascriptQuestions";

const DynamicQuestionList = dynamic(
  () => import("@/components/questions/QuestionList"),
  { ssr: false }
);

export default function Home() {
  return (
    <>
      <Head>
        <title>JavaScript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DynamicQuestionList
        questions={javascriptQuestionsData}
        tech="JavaScript"
      />
    </>
  );
}
